
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class SetupWebhookParameters {
    /**
    * Label: Trigger Id, type: entry
    */
    String ec_trigger

    static SetupWebhookParameters initParameters(StepParameters sp) {
        SetupWebhookParameters parameters = new SetupWebhookParameters()

        def ec_trigger = sp.getRequiredParameter('ec_trigger').value
        parameters.ec_trigger = ec_trigger

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: e19364c4f5ffe8861ec6e7a245ebe916 ===
